# Generated by Django 5.2.11 on 2026-02-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField(unique=True)),
                ("season", models.IntegerField()),
                ("kickoff_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("played", "Played")],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("home_goals", models.IntegerField(blank=True, null=True)),
                ("away_goals", models.IntegerField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HeadToHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField(blank=True, null=True)),
                ("last_n", models.IntegerField(default=5)),
                ("data", models.JSONField()),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("season", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_hash", models.CharField(max_length=64)),
                ("insight_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StandingsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("data", models.JSONField()),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="engine.league",
                    ),
                ),
            ],
            options={
                "unique_together": {("league", "season")},
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("venue_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="engine.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("last_n", models.IntegerField(default=5)),
                ("form_string", models.CharField(max_length=10)),
                ("goals_for_avg", models.FloatField()),
                ("goals_against_avg", models.FloatField()),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_cache",
                        to="engine.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "season", "last_n")},
            },
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AddField(
            model_name="fixture",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixtures",
                to="engine.league",
            ),
        ),
        migrations.AddField(
            model_name="matchinsight",
            name="fixture",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insight",
                to="engine.fixture",
            ),
        ),
        migrations.AddField(
            model_name="headtohead",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="h2h_away",
                to="engine.team",
            ),
        ),
        migrations.AddField(
            model_name="headtohead",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="h2h_home",
                to="engine.team",
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_fixtures",
                to="engine.team",
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_fixtures",
                to="engine.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="headtohead",
            unique_together={("home_team", "away_team", "last_n")},
        ),
    ]
