# Generated by Django 5.2.11 on 2026-02-10 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0002_fixture_headtohead_league_matchinsight_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form", models.CharField(max_length=150)),
                ("matches_played_home", models.IntegerField()),
                ("matches_played_away", models.IntegerField()),
                ("matches_played_total", models.IntegerField()),
                ("wins_home", models.IntegerField()),
                ("wins_away", models.IntegerField()),
                ("wins_total", models.IntegerField()),
                ("draws_home", models.IntegerField()),
                ("draws_away", models.IntegerField()),
                ("draws_total", models.IntegerField()),
                ("losses_home", models.IntegerField()),
                ("losses_away", models.IntegerField()),
                ("losses_total", models.IntegerField()),
                ("goals_home", models.IntegerField()),
                ("goals_away", models.IntegerField()),
                ("goals_total", models.IntegerField()),
                ("avg_goals_home", models.FloatField()),
                ("avg_goals_away", models.FloatField()),
                ("avg_goals_total", models.FloatField()),
                ("conceded_home", models.IntegerField()),
                ("conceded_away", models.IntegerField()),
                ("conceded_total", models.IntegerField()),
                ("avg_conceded_home", models.FloatField()),
                ("avg_conceded_away", models.FloatField()),
                ("avg_conceded_total", models.FloatField()),
                ("over_15", models.IntegerField()),
                ("under_15", models.IntegerField()),
                ("over_25", models.IntegerField()),
                ("under_25", models.IntegerField()),
                ("over_35", models.IntegerField()),
                ("under_35", models.IntegerField()),
                ("clean_sheet_home", models.IntegerField()),
                ("clean_sheet_away", models.IntegerField()),
                ("clean_sheet_total", models.IntegerField()),
                ("failed_to_score_home", models.IntegerField()),
                ("failed_to_score_away", models.IntegerField()),
                ("failed_to_score_total", models.IntegerField()),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teamstats",
                        to="engine.league",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teamstats",
                        to="engine.team",
                    ),
                ),
            ],
        ),
    ]
