# Generated by Django 5.2.11 on 2026-02-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0003_teamstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamstats",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="teamstats",
            unique_together={("league", "team")},
        ),
    ]
