# Generated by Django 5.2.11 on 2026-02-10 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0004_teamstats_updated_at_alter_teamstats_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("points", models.IntegerField()),
                ("goals_diff", models.IntegerField()),
                ("form", models.CharField(max_length=10)),
                ("played_total", models.IntegerField()),
                ("wins_total", models.IntegerField()),
                ("draws_total", models.IntegerField()),
                ("losses_total", models.IntegerField()),
                ("goals_for_total", models.IntegerField()),
                ("goals_against_total", models.IntegerField()),
                ("played_home", models.IntegerField()),
                ("wins_home", models.IntegerField()),
                ("draws_home", models.IntegerField()),
                ("losses_home", models.IntegerField()),
                ("goals_for_home", models.IntegerField()),
                ("goals_against_home", models.IntegerField()),
                ("played_away", models.IntegerField()),
                ("wins_away", models.IntegerField()),
                ("draws_away", models.IntegerField()),
                ("losses_away", models.IntegerField()),
                ("goals_for_away", models.IntegerField()),
                ("goals_against_away", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="engine.league",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="engine.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("league", "team", "season")},
            },
        ),
        migrations.DeleteModel(
            name="StandingsSnapshot",
        ),
    ]
