# Generated by Django 5.2.11 on 2026-02-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0005_standing_delete_standingssnapshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fixture",
            options={"ordering": ["date"]},
        ),
        migrations.RenameField(
            model_name="fixture",
            old_name="kickoff_time",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="fixture",
            old_name="away_goals",
            new_name="elapsed",
        ),
        migrations.RenameField(
            model_name="fixture",
            old_name="home_goals",
            new_name="extratime_away",
        ),
        migrations.RemoveField(
            model_name="fixture",
            name="api_id",
        ),
        migrations.RemoveField(
            model_name="fixture",
            name="away_team",
        ),
        migrations.RemoveField(
            model_name="fixture",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fixture",
            name="home_team",
        ),
        migrations.RemoveField(
            model_name="fixture",
            name="last_synced_at",
        ),
        migrations.RemoveField(
            model_name="fixture",
            name="league",
        ),
        migrations.RemoveField(
            model_name="fixture",
            name="season",
        ),
        migrations.RemoveField(
            model_name="fixture",
            name="status",
        ),
        migrations.AddField(
            model_name="fixture",
            name="away_team_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="away_winner",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="extratime_home",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="fixture_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="fulltime_away",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="fulltime_home",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="goals_away",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="goals_home",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="halftime_away",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="halftime_home",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="home_team_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="home_winner",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="league_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="league_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="league_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="league_round",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="league_season",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="penalty_away",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="penalty_home",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="referee",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="status_long",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="status_short",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="fixture",
            name="venue_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="venue_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="venue_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
