# Generated by Django 5.2.11 on 2026-02-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0006_alter_fixture_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="away_team_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="home_team_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
