# Generated by Django 5.2.11 on 2026-02-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0007_fixture_away_team_id_fixture_home_team_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
