# Generated by Django 5.2.11 on 2026-02-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0008_alter_fixture_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="H2HMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fixture_id", models.IntegerField(unique=True)),
                ("date", models.DateTimeField()),
                ("league_id", models.IntegerField()),
                ("league_name", models.CharField(max_length=255)),
                (
                    "league_round",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("home_team_id", models.IntegerField()),
                ("home_team_name", models.CharField(max_length=255)),
                ("away_team_id", models.IntegerField()),
                ("away_team_name", models.CharField(max_length=255)),
                ("home_goals", models.IntegerField(blank=True, null=True)),
                ("away_goals", models.IntegerField(blank=True, null=True)),
                ("status_short", models.CharField(max_length=10)),
                ("status_long", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["home_team_id", "away_team_id"],
                        name="h2h_home_away_idx",
                    ),
                    models.Index(fields=["league_id"], name="h2h_league_idx"),
                ],
            },
        ),
    ]
