# Generated by Django 5.2.11 on 2026-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0009_h2hmatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamFeatureStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.IntegerField()),
                ("team_name", models.CharField(max_length=150)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("venue_name", models.CharField(blank=True, max_length=150)),
                ("league_id", models.IntegerField()),
                ("league_name", models.CharField(max_length=150)),
                ("season", models.IntegerField()),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("points", models.IntegerField(blank=True, null=True)),
                ("goals_diff", models.IntegerField(blank=True, null=True)),
                ("played_total", models.IntegerField(blank=True, null=True)),
                ("played_home", models.IntegerField(blank=True, null=True)),
                ("played_away", models.IntegerField(blank=True, null=True)),
                ("wins_total", models.IntegerField(blank=True, null=True)),
                ("wins_home", models.IntegerField(blank=True, null=True)),
                ("wins_away", models.IntegerField(blank=True, null=True)),
                ("draws_total", models.IntegerField(blank=True, null=True)),
                ("draws_home", models.IntegerField(blank=True, null=True)),
                ("draws_away", models.IntegerField(blank=True, null=True)),
                ("losses_total", models.IntegerField(blank=True, null=True)),
                ("losses_home", models.IntegerField(blank=True, null=True)),
                ("losses_away", models.IntegerField(blank=True, null=True)),
                ("goals_for_total", models.IntegerField(blank=True, null=True)),
                ("goals_for_home", models.IntegerField(blank=True, null=True)),
                ("goals_for_away", models.IntegerField(blank=True, null=True)),
                ("goals_against_total", models.IntegerField(blank=True, null=True)),
                ("goals_against_home", models.IntegerField(blank=True, null=True)),
                ("goals_against_away", models.IntegerField(blank=True, null=True)),
                ("avg_goals_for_total", models.FloatField(blank=True, null=True)),
                ("avg_goals_for_home", models.FloatField(blank=True, null=True)),
                ("avg_goals_for_away", models.FloatField(blank=True, null=True)),
                ("avg_goals_against_total", models.FloatField(blank=True, null=True)),
                ("avg_goals_against_home", models.FloatField(blank=True, null=True)),
                ("avg_goals_against_away", models.FloatField(blank=True, null=True)),
                ("clean_sheets_total", models.IntegerField(blank=True, null=True)),
                ("clean_sheets_home", models.IntegerField(blank=True, null=True)),
                ("clean_sheets_away", models.IntegerField(blank=True, null=True)),
                ("failed_to_score_total", models.IntegerField(blank=True, null=True)),
                ("failed_to_score_home", models.IntegerField(blank=True, null=True)),
                ("failed_to_score_away", models.IntegerField(blank=True, null=True)),
                ("over_15", models.IntegerField(blank=True, null=True)),
                ("under_15", models.IntegerField(blank=True, null=True)),
                ("over_25", models.IntegerField(blank=True, null=True)),
                ("under_25", models.IntegerField(blank=True, null=True)),
                ("over_35", models.IntegerField(blank=True, null=True)),
                ("under_35", models.IntegerField(blank=True, null=True)),
                (
                    "last_form_string",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("last_goals_for_avg", models.FloatField(blank=True, null=True)),
                ("last_goals_against_avg", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team_id", "league_id"], name="team_feature_store_idx"
                    )
                ],
                "unique_together": {("team_id", "league_id", "season")},
            },
        ),
        migrations.DeleteModel(
            name="HeadToHead",
        ),
    ]
