# Generated by Django 5.2.11 on 2026-02-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0011_teamfeaturestoreadmin_delete_teamfeaturestore_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamFeatureStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("team_name", models.CharField(max_length=100)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("venue_name", models.CharField(blank=True, max_length=150)),
                ("matches_played_home", models.IntegerField()),
                ("matches_played_away", models.IntegerField()),
                ("matches_played_total", models.IntegerField()),
                ("wins_home", models.IntegerField()),
                ("wins_away", models.IntegerField()),
                ("wins_total", models.IntegerField()),
                ("draws_home", models.IntegerField()),
                ("draws_away", models.IntegerField()),
                ("draws_total", models.IntegerField()),
                ("losses_home", models.IntegerField()),
                ("losses_away", models.IntegerField()),
                ("losses_total", models.IntegerField()),
                ("goals_home", models.IntegerField()),
                ("goals_away", models.IntegerField()),
                ("goals_total", models.IntegerField()),
                ("avg_goals_home", models.FloatField()),
                ("avg_goals_away", models.FloatField()),
                ("avg_goals_total", models.FloatField()),
                ("conceded_home", models.IntegerField()),
                ("conceded_away", models.IntegerField()),
                ("conceded_total", models.IntegerField()),
                ("avg_conceded_home", models.FloatField()),
                ("avg_conceded_away", models.FloatField()),
                ("avg_conceded_total", models.FloatField()),
                ("over_15", models.IntegerField()),
                ("under_15", models.IntegerField()),
                ("over_25", models.IntegerField()),
                ("under_25", models.IntegerField()),
                ("over_35", models.IntegerField()),
                ("under_35", models.IntegerField()),
                ("clean_sheet_home", models.IntegerField()),
                ("clean_sheet_away", models.IntegerField()),
                ("clean_sheet_total", models.IntegerField()),
                ("failed_to_score_home", models.IntegerField()),
                ("failed_to_score_away", models.IntegerField()),
                ("failed_to_score_total", models.IntegerField()),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("points", models.IntegerField(blank=True, null=True)),
                ("goals_diff", models.IntegerField(blank=True, null=True)),
                ("form", models.CharField(blank=True, max_length=10)),
                ("last_5_form", models.CharField(blank=True, max_length=10)),
                ("last_5_matches_played", models.IntegerField(default=0)),
                ("last_5_wins", models.IntegerField(default=0)),
                ("last_5_draws", models.IntegerField(default=0)),
                ("last_5_losses", models.IntegerField(default=0)),
                ("last_5_goals_for", models.IntegerField(default=0)),
                ("last_5_goals_against", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="engine.league",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="engine.team",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TeamFeatureStoreAdmin",
        ),
        migrations.AddIndex(
            model_name="teamfeaturestore",
            index=models.Index(
                fields=["team", "league", "season"], name="team_feature_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamfeaturestore",
            unique_together={("team", "league", "season")},
        ),
    ]
