# Generated by Django 5.2.11 on 2026-02-11 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0012_teamfeaturestore_delete_teamfeaturestoreadmin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standing",
            old_name="form",
            new_name="last_5_form",
        ),
    ]
