# Generated by Django 5.2.11 on 2026-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0013_rename_form_standing_last_5_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="season",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="season",
            field=models.IntegerField(default=2023),
        ),
    ]
