# Generated by Django 5.2.11 on 2026-02-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0014_fixture_season_teamstats_season"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamstats",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="fixture",
            name="season",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="teamstats",
            name="season",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="teamstats",
            unique_together={("league", "team", "season")},
        ),
    ]
