# Generated by Django 5.2.11 on 2026-04-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "engine",
            "0015_alter_teamstats_unique_together_alter_fixture_season_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="matchinsight",
            name="btts_probability",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matchinsight",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matchinsight",
            name="over_25_probability",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matchinsight",
            name="predicted_winner",
            field=models.CharField(
                blank=True,
                choices=[("home", "Home"), ("away", "Away"), ("draw", "Draw")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matchinsight",
            name="recommended_bet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="matchinsight",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
