# Generated by Django 5.2.11 on 2026-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0016_matchinsight_btts_probability_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("subscription_start", models.DateTimeField(blank=True, null=True)),
                ("subscription_end", models.DateTimeField(blank=True, null=True)),
                (
                    "paystack_customer_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paystack_subscription_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
